---
- name: Clear logs
  ignore_errors: true
  hosts: all
  tasks:
    - name: Install gzip
      package:
        name: gzip



    - name: Zip log file
      shell: 'find / -size +1G 2>/dev/null  -name "*.log" -exec gzip -v9 {} \;'
