---
- name: Change file content
  ignore_errors: true
  hosts: localhost
  tasks:
    - name: Change /tmp/file
      lineinfile: 
        path: /tmp/file
        regexp: '^hello'
        line: "hello world"
        create: yes

